//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminWebStatus) DeepCopyInto(out *AdminWebStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminWebStatus.
func (in *AdminWebStatus) DeepCopy() *AdminWebStatus {
	if in == nil {
		return nil
	}
	out := new(AdminWebStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupConfig) DeepCopyInto(out *BackupConfig) {
	*out = *in
	if in.Filesystem != nil {
		in, out := &in.Filesystem, &out.Filesystem
		*out = new(FilesystemBackupConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3BackupConfig)
		**out = **in
	}
	if in.PgBackRestTLS != nil {
		in, out := &in.PgBackRestTLS, &out.PgBackRestTLS
		*out = new(PgBackRestTLSConfig)
		**out = **in
	}
	if in.Encryption != nil {
		in, out := &in.Encryption, &out.Encryption
		*out = new(BackupEncryptionConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupConfig.
func (in *BackupConfig) DeepCopy() *BackupConfig {
	if in == nil {
		return nil
	}
	out := new(BackupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupEncryptionConfig) DeepCopyInto(out *BackupEncryptionConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupEncryptionConfig.
func (in *BackupEncryptionConfig) DeepCopy() *BackupEncryptionConfig {
	if in == nil {
		return nil
	}
	out := new(BackupEncryptionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cell) DeepCopyInto(out *Cell) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cell.
func (in *Cell) DeepCopy() *Cell {
	if in == nil {
		return nil
	}
	out := new(Cell)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cell) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CellConfig) DeepCopyInto(out *CellConfig) {
	*out = *in
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(CellOverrides)
		(*in).DeepCopyInto(*out)
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(CellInlineSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CellConfig.
func (in *CellConfig) DeepCopy() *CellConfig {
	if in == nil {
		return nil
	}
	out := new(CellConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CellImages) DeepCopyInto(out *CellImages) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CellImages.
func (in *CellImages) DeepCopy() *CellImages {
	if in == nil {
		return nil
	}
	out := new(CellImages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CellInlineSpec) DeepCopyInto(out *CellInlineSpec) {
	*out = *in
	in.Multigateway.DeepCopyInto(&out.Multigateway)
	if in.MultigatewayPlacement != nil {
		in, out := &in.MultigatewayPlacement, &out.MultigatewayPlacement
		*out = new(PodPlacementSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.LocalTopoServer != nil {
		in, out := &in.LocalTopoServer, &out.LocalTopoServer
		*out = new(LocalTopoServerSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CellInlineSpec.
func (in *CellInlineSpec) DeepCopy() *CellInlineSpec {
	if in == nil {
		return nil
	}
	out := new(CellInlineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CellList) DeepCopyInto(out *CellList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cell, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CellList.
func (in *CellList) DeepCopy() *CellList {
	if in == nil {
		return nil
	}
	out := new(CellList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CellList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CellOverrides) DeepCopyInto(out *CellOverrides) {
	*out = *in
	if in.Multigateway != nil {
		in, out := &in.Multigateway, &out.Multigateway
		*out = new(StatelessSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MultigatewayPlacement != nil {
		in, out := &in.MultigatewayPlacement, &out.MultigatewayPlacement
		*out = new(PodPlacementSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CellOverrides.
func (in *CellOverrides) DeepCopy() *CellOverrides {
	if in == nil {
		return nil
	}
	out := new(CellOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CellSpec) DeepCopyInto(out *CellSpec) {
	*out = *in
	in.Images.DeepCopyInto(&out.Images)
	in.Multigateway.DeepCopyInto(&out.Multigateway)
	if in.MultigatewayPlacement != nil {
		in, out := &in.MultigatewayPlacement, &out.MultigatewayPlacement
		*out = new(PodPlacementSpec)
		(*in).DeepCopyInto(*out)
	}
	out.GlobalTopoServer = in.GlobalTopoServer
	if in.TopoServer != nil {
		in, out := &in.TopoServer, &out.TopoServer
		*out = new(LocalTopoServerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.AllCells != nil {
		in, out := &in.AllCells, &out.AllCells
		*out = make([]CellName, len(*in))
		copy(*out, *in)
	}
	out.TopologyReconciliation = in.TopologyReconciliation
	if in.Observability != nil {
		in, out := &in.Observability, &out.Observability
		*out = new(ObservabilityConfig)
		(*in).DeepCopyInto(*out)
	}
	out.LogLevels = in.LogLevels
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CellSpec.
func (in *CellSpec) DeepCopy() *CellSpec {
	if in == nil {
		return nil
	}
	out := new(CellSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CellStatus) DeepCopyInto(out *CellStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CellStatus.
func (in *CellStatus) DeepCopy() *CellStatus {
	if in == nil {
		return nil
	}
	out := new(CellStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CellStatusSummary) DeepCopyInto(out *CellStatusSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CellStatusSummary.
func (in *CellStatusSummary) DeepCopy() *CellStatusSummary {
	if in == nil {
		return nil
	}
	out := new(CellStatusSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CellTemplate) DeepCopyInto(out *CellTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CellTemplate.
func (in *CellTemplate) DeepCopy() *CellTemplate {
	if in == nil {
		return nil
	}
	out := new(CellTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CellTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CellTemplateList) DeepCopyInto(out *CellTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CellTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CellTemplateList.
func (in *CellTemplateList) DeepCopy() *CellTemplateList {
	if in == nil {
		return nil
	}
	out := new(CellTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CellTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CellTemplateSpec) DeepCopyInto(out *CellTemplateSpec) {
	*out = *in
	if in.Multigateway != nil {
		in, out := &in.Multigateway, &out.Multigateway
		*out = new(StatelessSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MultigatewayPlacement != nil {
		in, out := &in.MultigatewayPlacement, &out.MultigatewayPlacement
		*out = new(PodPlacementSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.LocalTopoServer != nil {
		in, out := &in.LocalTopoServer, &out.LocalTopoServer
		*out = new(LocalTopoServerSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CellTemplateSpec.
func (in *CellTemplateSpec) DeepCopy() *CellTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(CellTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterImages) DeepCopyInto(out *ClusterImages) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterImages.
func (in *ClusterImages) DeepCopy() *ClusterImages {
	if in == nil {
		return nil
	}
	out := new(ClusterImages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentLogLevels) DeepCopyInto(out *ComponentLogLevels) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentLogLevels.
func (in *ComponentLogLevels) DeepCopy() *ComponentLogLevels {
	if in == nil {
		return nil
	}
	out := new(ComponentLogLevels)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerConfig) DeepCopyInto(out *ContainerConfig) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerConfig.
func (in *ContainerConfig) DeepCopy() *ContainerConfig {
	if in == nil {
		return nil
	}
	out := new(ContainerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreTemplate) DeepCopyInto(out *CoreTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreTemplate.
func (in *CoreTemplate) DeepCopy() *CoreTemplate {
	if in == nil {
		return nil
	}
	out := new(CoreTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CoreTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreTemplateList) DeepCopyInto(out *CoreTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CoreTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreTemplateList.
func (in *CoreTemplateList) DeepCopy() *CoreTemplateList {
	if in == nil {
		return nil
	}
	out := new(CoreTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CoreTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreTemplateSpec) DeepCopyInto(out *CoreTemplateSpec) {
	*out = *in
	if in.GlobalTopoServer != nil {
		in, out := &in.GlobalTopoServer, &out.GlobalTopoServer
		*out = new(TopoServerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Multiadmin != nil {
		in, out := &in.Multiadmin, &out.Multiadmin
		*out = new(StatelessSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MultiadminWeb != nil {
		in, out := &in.MultiadminWeb, &out.MultiadminWeb
		*out = new(StatelessSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreTemplateSpec.
func (in *CoreTemplateSpec) DeepCopy() *CoreTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(CoreTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseConfig) DeepCopyInto(out *DatabaseConfig) {
	*out = *in
	if in.TableGroups != nil {
		in, out := &in.TableGroups, &out.TableGroups
		*out = make([]TableGroupConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(BackupConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseConfig.
func (in *DatabaseConfig) DeepCopy() *DatabaseConfig {
	if in == nil {
		return nil
	}
	out := new(DatabaseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseStatusSummary) DeepCopyInto(out *DatabaseStatusSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseStatusSummary.
func (in *DatabaseStatusSummary) DeepCopy() *DatabaseStatusSummary {
	if in == nil {
		return nil
	}
	out := new(DatabaseStatusSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EtcdSpec) DeepCopyInto(out *EtcdSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Storage.DeepCopyInto(&out.Storage)
	in.Resources.DeepCopyInto(&out.Resources)
	if in.PVCDeletionPolicy != nil {
		in, out := &in.PVCDeletionPolicy, &out.PVCDeletionPolicy
		*out = new(PVCDeletionPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EtcdSpec.
func (in *EtcdSpec) DeepCopy() *EtcdSpec {
	if in == nil {
		return nil
	}
	out := new(EtcdSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalAdminWebConfig) DeepCopyInto(out *ExternalAdminWebConfig) {
	*out = *in
	if in.ExternalIPs != nil {
		in, out := &in.ExternalIPs, &out.ExternalIPs
		*out = make([]IPAddress, len(*in))
		copy(*out, *in)
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalAdminWebConfig.
func (in *ExternalAdminWebConfig) DeepCopy() *ExternalAdminWebConfig {
	if in == nil {
		return nil
	}
	out := new(ExternalAdminWebConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalGatewayConfig) DeepCopyInto(out *ExternalGatewayConfig) {
	*out = *in
	if in.ExternalIPs != nil {
		in, out := &in.ExternalIPs, &out.ExternalIPs
		*out = make([]IPAddress, len(*in))
		copy(*out, *in)
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalGatewayConfig.
func (in *ExternalGatewayConfig) DeepCopy() *ExternalGatewayConfig {
	if in == nil {
		return nil
	}
	out := new(ExternalGatewayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalTopoServerSpec) DeepCopyInto(out *ExternalTopoServerSpec) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]EndpointUrl, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalTopoServerSpec.
func (in *ExternalTopoServerSpec) DeepCopy() *ExternalTopoServerSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalTopoServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilesystemBackupConfig) DeepCopyInto(out *FilesystemBackupConfig) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilesystemBackupConfig.
func (in *FilesystemBackupConfig) DeepCopy() *FilesystemBackupConfig {
	if in == nil {
		return nil
	}
	out := new(FilesystemBackupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayStatus) DeepCopyInto(out *GatewayStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayStatus.
func (in *GatewayStatus) DeepCopy() *GatewayStatus {
	if in == nil {
		return nil
	}
	out := new(GatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalTopoServerRef) DeepCopyInto(out *GlobalTopoServerRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalTopoServerRef.
func (in *GlobalTopoServerRef) DeepCopy() *GlobalTopoServerRef {
	if in == nil {
		return nil
	}
	out := new(GlobalTopoServerRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalTopoServerSpec) DeepCopyInto(out *GlobalTopoServerSpec) {
	*out = *in
	if in.Etcd != nil {
		in, out := &in.Etcd, &out.Etcd
		*out = new(EtcdSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalTopoServerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PVCDeletionPolicy != nil {
		in, out := &in.PVCDeletionPolicy, &out.PVCDeletionPolicy
		*out = new(PVCDeletionPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalTopoServerSpec.
func (in *GlobalTopoServerSpec) DeepCopy() *GlobalTopoServerSpec {
	if in == nil {
		return nil
	}
	out := new(GlobalTopoServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalTopoServerSpec) DeepCopyInto(out *LocalTopoServerSpec) {
	*out = *in
	if in.Etcd != nil {
		in, out := &in.Etcd, &out.Etcd
		*out = new(EtcdSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalTopoServerSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalTopoServerSpec.
func (in *LocalTopoServerSpec) DeepCopy() *LocalTopoServerSpec {
	if in == nil {
		return nil
	}
	out := new(LocalTopoServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiadminConfig) DeepCopyInto(out *MultiadminConfig) {
	*out = *in
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(StatelessSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiadminConfig.
func (in *MultiadminConfig) DeepCopy() *MultiadminConfig {
	if in == nil {
		return nil
	}
	out := new(MultiadminConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiadminWebConfig) DeepCopyInto(out *MultiadminWebConfig) {
	*out = *in
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(StatelessSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiadminWebConfig.
func (in *MultiadminWebConfig) DeepCopy() *MultiadminWebConfig {
	if in == nil {
		return nil
	}
	out := new(MultiadminWebConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultigresCluster) DeepCopyInto(out *MultigresCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultigresCluster.
func (in *MultigresCluster) DeepCopy() *MultigresCluster {
	if in == nil {
		return nil
	}
	out := new(MultigresCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MultigresCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultigresClusterList) DeepCopyInto(out *MultigresClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MultigresCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultigresClusterList.
func (in *MultigresClusterList) DeepCopy() *MultigresClusterList {
	if in == nil {
		return nil
	}
	out := new(MultigresClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MultigresClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultigresClusterSpec) DeepCopyInto(out *MultigresClusterSpec) {
	*out = *in
	in.Images.DeepCopyInto(&out.Images)
	out.LogLevels = in.LogLevels
	out.TemplateDefaults = in.TemplateDefaults
	if in.GlobalTopoServer != nil {
		in, out := &in.GlobalTopoServer, &out.GlobalTopoServer
		*out = new(GlobalTopoServerSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Multiadmin != nil {
		in, out := &in.Multiadmin, &out.Multiadmin
		*out = new(MultiadminConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MultiadminWeb != nil {
		in, out := &in.MultiadminWeb, &out.MultiadminWeb
		*out = new(MultiadminWebConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Cells != nil {
		in, out := &in.Cells, &out.Cells
		*out = make([]CellConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Databases != nil {
		in, out := &in.Databases, &out.Databases
		*out = make([]DatabaseConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PVCDeletionPolicy != nil {
		in, out := &in.PVCDeletionPolicy, &out.PVCDeletionPolicy
		*out = new(PVCDeletionPolicy)
		**out = **in
	}
	if in.Observability != nil {
		in, out := &in.Observability, &out.Observability
		*out = new(ObservabilityConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(BackupConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ExternalGateway != nil {
		in, out := &in.ExternalGateway, &out.ExternalGateway
		*out = new(ExternalGatewayConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ExternalAdminWeb != nil {
		in, out := &in.ExternalAdminWeb, &out.ExternalAdminWeb
		*out = new(ExternalAdminWebConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.TopologyPruning != nil {
		in, out := &in.TopologyPruning, &out.TopologyPruning
		*out = new(TopologyPruningConfig)
		(*in).DeepCopyInto(*out)
	}
	out.PostgresPasswordSecretRef = in.PostgresPasswordSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultigresClusterSpec.
func (in *MultigresClusterSpec) DeepCopy() *MultigresClusterSpec {
	if in == nil {
		return nil
	}
	out := new(MultigresClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultigresClusterStatus) DeepCopyInto(out *MultigresClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Cells != nil {
		in, out := &in.Cells, &out.Cells
		*out = make(map[CellName]CellStatusSummary, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(GatewayStatus)
		**out = **in
	}
	if in.AdminWeb != nil {
		in, out := &in.AdminWeb, &out.AdminWeb
		*out = new(AdminWebStatus)
		**out = **in
	}
	if in.Databases != nil {
		in, out := &in.Databases, &out.Databases
		*out = make(map[DatabaseName]DatabaseStatusSummary, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ResolvedTemplates != nil {
		in, out := &in.ResolvedTemplates, &out.ResolvedTemplates
		*out = new(ResolvedTemplates)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultigresClusterStatus.
func (in *MultigresClusterStatus) DeepCopy() *MultigresClusterStatus {
	if in == nil {
		return nil
	}
	out := new(MultigresClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiorchSpec) DeepCopyInto(out *MultiorchSpec) {
	*out = *in
	in.StatelessSpec.DeepCopyInto(&out.StatelessSpec)
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(PodPlacementSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Cells != nil {
		in, out := &in.Cells, &out.Cells
		*out = make([]CellName, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiorchSpec.
func (in *MultiorchSpec) DeepCopy() *MultiorchSpec {
	if in == nil {
		return nil
	}
	out := new(MultiorchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservabilityConfig) DeepCopyInto(out *ObservabilityConfig) {
	*out = *in
	if in.SamplingConfigRef != nil {
		in, out := &in.SamplingConfigRef, &out.SamplingConfigRef
		*out = new(SamplingConfigRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservabilityConfig.
func (in *ObservabilityConfig) DeepCopy() *ObservabilityConfig {
	if in == nil {
		return nil
	}
	out := new(ObservabilityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCDeletionPolicy) DeepCopyInto(out *PVCDeletionPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCDeletionPolicy.
func (in *PVCDeletionPolicy) DeepCopy() *PVCDeletionPolicy {
	if in == nil {
		return nil
	}
	out := new(PVCDeletionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgBackRestTLSConfig) DeepCopyInto(out *PgBackRestTLSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgBackRestTLSConfig.
func (in *PgBackRestTLSConfig) DeepCopy() *PgBackRestTLSConfig {
	if in == nil {
		return nil
	}
	out := new(PgBackRestTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodPlacementSpec) DeepCopyInto(out *PodPlacementSpec) {
	*out = *in
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodPlacementSpec.
func (in *PodPlacementSpec) DeepCopy() *PodPlacementSpec {
	if in == nil {
		return nil
	}
	out := new(PodPlacementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolSpec) DeepCopyInto(out *PoolSpec) {
	*out = *in
	if in.Cells != nil {
		in, out := &in.Cells, &out.Cells
		*out = make([]CellName, len(*in))
		copy(*out, *in)
	}
	if in.ReplicasPerCell != nil {
		in, out := &in.ReplicasPerCell, &out.ReplicasPerCell
		*out = new(int32)
		**out = **in
	}
	in.Storage.DeepCopyInto(&out.Storage)
	in.Postgres.DeepCopyInto(&out.Postgres)
	in.Multipooler.DeepCopyInto(&out.Multipooler)
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FSGroup != nil {
		in, out := &in.FSGroup, &out.FSGroup
		*out = new(int64)
		**out = **in
	}
	if in.PVCDeletionPolicy != nil {
		in, out := &in.PVCDeletionPolicy, &out.PVCDeletionPolicy
		*out = new(PVCDeletionPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolSpec.
func (in *PoolSpec) DeepCopy() *PoolSpec {
	if in == nil {
		return nil
	}
	out := new(PoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresConfigRef) DeepCopyInto(out *PostgresConfigRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresConfigRef.
func (in *PostgresConfigRef) DeepCopy() *PostgresConfigRef {
	if in == nil {
		return nil
	}
	out := new(PostgresConfigRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresPasswordSecretRef) DeepCopyInto(out *PostgresPasswordSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresPasswordSecretRef.
func (in *PostgresPasswordSecretRef) DeepCopy() *PostgresPasswordSecretRef {
	if in == nil {
		return nil
	}
	out := new(PostgresPasswordSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedTemplates) DeepCopyInto(out *ResolvedTemplates) {
	*out = *in
	if in.CoreTemplates != nil {
		in, out := &in.CoreTemplates, &out.CoreTemplates
		*out = make([]TemplateRef, len(*in))
		copy(*out, *in)
	}
	if in.CellTemplates != nil {
		in, out := &in.CellTemplates, &out.CellTemplates
		*out = make([]TemplateRef, len(*in))
		copy(*out, *in)
	}
	if in.ShardTemplates != nil {
		in, out := &in.ShardTemplates, &out.ShardTemplates
		*out = make([]TemplateRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedTemplates.
func (in *ResolvedTemplates) DeepCopy() *ResolvedTemplates {
	if in == nil {
		return nil
	}
	out := new(ResolvedTemplates)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3BackupConfig) DeepCopyInto(out *S3BackupConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3BackupConfig.
func (in *S3BackupConfig) DeepCopy() *S3BackupConfig {
	if in == nil {
		return nil
	}
	out := new(S3BackupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SamplingConfigRef) DeepCopyInto(out *SamplingConfigRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SamplingConfigRef.
func (in *SamplingConfigRef) DeepCopy() *SamplingConfigRef {
	if in == nil {
		return nil
	}
	out := new(SamplingConfigRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Shard) DeepCopyInto(out *Shard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Shard.
func (in *Shard) DeepCopy() *Shard {
	if in == nil {
		return nil
	}
	out := new(Shard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Shard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardConfig) DeepCopyInto(out *ShardConfig) {
	*out = *in
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(ShardOverrides)
		(*in).DeepCopyInto(*out)
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(ShardInlineSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(BackupConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardConfig.
func (in *ShardConfig) DeepCopy() *ShardConfig {
	if in == nil {
		return nil
	}
	out := new(ShardConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardImages) DeepCopyInto(out *ShardImages) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]v1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardImages.
func (in *ShardImages) DeepCopy() *ShardImages {
	if in == nil {
		return nil
	}
	out := new(ShardImages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardInlineSpec) DeepCopyInto(out *ShardInlineSpec) {
	*out = *in
	in.Multiorch.DeepCopyInto(&out.Multiorch)
	if in.PostgresConfigRef != nil {
		in, out := &in.PostgresConfigRef, &out.PostgresConfigRef
		*out = new(PostgresConfigRef)
		**out = **in
	}
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make(map[PoolName]PoolSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.PVCDeletionPolicy != nil {
		in, out := &in.PVCDeletionPolicy, &out.PVCDeletionPolicy
		*out = new(PVCDeletionPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardInlineSpec.
func (in *ShardInlineSpec) DeepCopy() *ShardInlineSpec {
	if in == nil {
		return nil
	}
	out := new(ShardInlineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardList) DeepCopyInto(out *ShardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Shard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardList.
func (in *ShardList) DeepCopy() *ShardList {
	if in == nil {
		return nil
	}
	out := new(ShardList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardOverrides) DeepCopyInto(out *ShardOverrides) {
	*out = *in
	if in.Multiorch != nil {
		in, out := &in.Multiorch, &out.Multiorch
		*out = new(MultiorchSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PostgresConfigRef != nil {
		in, out := &in.PostgresConfigRef, &out.PostgresConfigRef
		*out = new(PostgresConfigRef)
		**out = **in
	}
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make(map[PoolName]PoolSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardOverrides.
func (in *ShardOverrides) DeepCopy() *ShardOverrides {
	if in == nil {
		return nil
	}
	out := new(ShardOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardResolvedSpec) DeepCopyInto(out *ShardResolvedSpec) {
	*out = *in
	in.Multiorch.DeepCopyInto(&out.Multiorch)
	if in.PostgresConfigRef != nil {
		in, out := &in.PostgresConfigRef, &out.PostgresConfigRef
		*out = new(PostgresConfigRef)
		**out = **in
	}
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make(map[PoolName]PoolSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.PVCDeletionPolicy != nil {
		in, out := &in.PVCDeletionPolicy, &out.PVCDeletionPolicy
		*out = new(PVCDeletionPolicy)
		**out = **in
	}
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(BackupConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardResolvedSpec.
func (in *ShardResolvedSpec) DeepCopy() *ShardResolvedSpec {
	if in == nil {
		return nil
	}
	out := new(ShardResolvedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardSpec) DeepCopyInto(out *ShardSpec) {
	*out = *in
	in.Images.DeepCopyInto(&out.Images)
	out.GlobalTopoServer = in.GlobalTopoServer
	in.Multiorch.DeepCopyInto(&out.Multiorch)
	if in.PostgresConfigRef != nil {
		in, out := &in.PostgresConfigRef, &out.PostgresConfigRef
		*out = new(PostgresConfigRef)
		**out = **in
	}
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make(map[PoolName]PoolSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.PVCDeletionPolicy != nil {
		in, out := &in.PVCDeletionPolicy, &out.PVCDeletionPolicy
		*out = new(PVCDeletionPolicy)
		**out = **in
	}
	if in.Observability != nil {
		in, out := &in.Observability, &out.Observability
		*out = new(ObservabilityConfig)
		(*in).DeepCopyInto(*out)
	}
	out.LogLevels = in.LogLevels
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(BackupConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.TopologyPruning != nil {
		in, out := &in.TopologyPruning, &out.TopologyPruning
		*out = new(TopologyPruningConfig)
		(*in).DeepCopyInto(*out)
	}
	out.PostgresPasswordSecretRef = in.PostgresPasswordSecretRef
	if in.CellTopologyLabels != nil {
		in, out := &in.CellTopologyLabels, &out.CellTopologyLabels
		*out = make(map[CellName]map[string]string, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardSpec.
func (in *ShardSpec) DeepCopy() *ShardSpec {
	if in == nil {
		return nil
	}
	out := new(ShardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardStatus) DeepCopyInto(out *ShardStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Cells != nil {
		in, out := &in.Cells, &out.Cells
		*out = make([]CellName, len(*in))
		copy(*out, *in)
	}
	if in.LastBackupTime != nil {
		in, out := &in.LastBackupTime, &out.LastBackupTime
		*out = (*in).DeepCopy()
	}
	if in.PodRoles != nil {
		in, out := &in.PodRoles, &out.PodRoles
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardStatus.
func (in *ShardStatus) DeepCopy() *ShardStatus {
	if in == nil {
		return nil
	}
	out := new(ShardStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardTemplate) DeepCopyInto(out *ShardTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardTemplate.
func (in *ShardTemplate) DeepCopy() *ShardTemplate {
	if in == nil {
		return nil
	}
	out := new(ShardTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShardTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardTemplateList) DeepCopyInto(out *ShardTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ShardTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardTemplateList.
func (in *ShardTemplateList) DeepCopy() *ShardTemplateList {
	if in == nil {
		return nil
	}
	out := new(ShardTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShardTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardTemplateSpec) DeepCopyInto(out *ShardTemplateSpec) {
	*out = *in
	if in.Multiorch != nil {
		in, out := &in.Multiorch, &out.Multiorch
		*out = new(MultiorchSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PostgresConfigRef != nil {
		in, out := &in.PostgresConfigRef, &out.PostgresConfigRef
		*out = new(PostgresConfigRef)
		**out = **in
	}
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make(map[PoolName]PoolSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.PVCDeletionPolicy != nil {
		in, out := &in.PVCDeletionPolicy, &out.PVCDeletionPolicy
		*out = new(PVCDeletionPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardTemplateSpec.
func (in *ShardTemplateSpec) DeepCopy() *ShardTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ShardTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatelessSpec) DeepCopyInto(out *StatelessSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodLabels != nil {
		in, out := &in.PodLabels, &out.PodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatelessSpec.
func (in *StatelessSpec) DeepCopy() *StatelessSpec {
	if in == nil {
		return nil
	}
	out := new(StatelessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]v1.PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableGroup) DeepCopyInto(out *TableGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableGroup.
func (in *TableGroup) DeepCopy() *TableGroup {
	if in == nil {
		return nil
	}
	out := new(TableGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TableGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableGroupConfig) DeepCopyInto(out *TableGroupConfig) {
	*out = *in
	if in.Shards != nil {
		in, out := &in.Shards, &out.Shards
		*out = make([]ShardConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(BackupConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.PVCDeletionPolicy != nil {
		in, out := &in.PVCDeletionPolicy, &out.PVCDeletionPolicy
		*out = new(PVCDeletionPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableGroupConfig.
func (in *TableGroupConfig) DeepCopy() *TableGroupConfig {
	if in == nil {
		return nil
	}
	out := new(TableGroupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableGroupList) DeepCopyInto(out *TableGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TableGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableGroupList.
func (in *TableGroupList) DeepCopy() *TableGroupList {
	if in == nil {
		return nil
	}
	out := new(TableGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TableGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableGroupSpec) DeepCopyInto(out *TableGroupSpec) {
	*out = *in
	in.Images.DeepCopyInto(&out.Images)
	out.GlobalTopoServer = in.GlobalTopoServer
	if in.Shards != nil {
		in, out := &in.Shards, &out.Shards
		*out = make([]ShardResolvedSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PVCDeletionPolicy != nil {
		in, out := &in.PVCDeletionPolicy, &out.PVCDeletionPolicy
		*out = new(PVCDeletionPolicy)
		**out = **in
	}
	if in.Observability != nil {
		in, out := &in.Observability, &out.Observability
		*out = new(ObservabilityConfig)
		(*in).DeepCopyInto(*out)
	}
	out.LogLevels = in.LogLevels
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(BackupConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CellTopologyLabels != nil {
		in, out := &in.CellTopologyLabels, &out.CellTopologyLabels
		*out = make(map[CellName]map[string]string, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.TopologyPruning != nil {
		in, out := &in.TopologyPruning, &out.TopologyPruning
		*out = new(TopologyPruningConfig)
		(*in).DeepCopyInto(*out)
	}
	out.PostgresPasswordSecretRef = in.PostgresPasswordSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableGroupSpec.
func (in *TableGroupSpec) DeepCopy() *TableGroupSpec {
	if in == nil {
		return nil
	}
	out := new(TableGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TableGroupStatus) DeepCopyInto(out *TableGroupStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TableGroupStatus.
func (in *TableGroupStatus) DeepCopy() *TableGroupStatus {
	if in == nil {
		return nil
	}
	out := new(TableGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateDefaults) DeepCopyInto(out *TemplateDefaults) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateDefaults.
func (in *TemplateDefaults) DeepCopy() *TemplateDefaults {
	if in == nil {
		return nil
	}
	out := new(TemplateDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopoServer) DeepCopyInto(out *TopoServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopoServer.
func (in *TopoServer) DeepCopy() *TopoServer {
	if in == nil {
		return nil
	}
	out := new(TopoServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TopoServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopoServerList) DeepCopyInto(out *TopoServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TopoServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopoServerList.
func (in *TopoServerList) DeepCopy() *TopoServerList {
	if in == nil {
		return nil
	}
	out := new(TopoServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TopoServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopoServerSpec) DeepCopyInto(out *TopoServerSpec) {
	*out = *in
	if in.Etcd != nil {
		in, out := &in.Etcd, &out.Etcd
		*out = new(EtcdSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PVCDeletionPolicy != nil {
		in, out := &in.PVCDeletionPolicy, &out.PVCDeletionPolicy
		*out = new(PVCDeletionPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopoServerSpec.
func (in *TopoServerSpec) DeepCopy() *TopoServerSpec {
	if in == nil {
		return nil
	}
	out := new(TopoServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopoServerStatus) DeepCopyInto(out *TopoServerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopoServerStatus.
func (in *TopoServerStatus) DeepCopy() *TopoServerStatus {
	if in == nil {
		return nil
	}
	out := new(TopoServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyPruningConfig) DeepCopyInto(out *TopologyPruningConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyPruningConfig.
func (in *TopologyPruningConfig) DeepCopy() *TopologyPruningConfig {
	if in == nil {
		return nil
	}
	out := new(TopologyPruningConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyReconciliation) DeepCopyInto(out *TopologyReconciliation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyReconciliation.
func (in *TopologyReconciliation) DeepCopy() *TopologyReconciliation {
	if in == nil {
		return nil
	}
	out := new(TopologyReconciliation)
	in.DeepCopyInto(out)
	return out
}
